### ISSUE TITLE
Issues with instalation

### ISSUE THREAD

**Issue by tdouthat** [foss-transportationmodeling/popgen#4]
I'm getting this error, any insights? 

C:\Users\tdouthat3\Desktop\popgen-2.0.b2> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import popgen
  File "C:\Users\tdouthat3\Desktop\popgen-2.0.b2\popgen\__init__.py", line 1, in <module>
    from .project import Project
  File "C:\Users\tdouthat3\Desktop\popgen-2.0.b2\popgen\project.py", line 50
    print "Running Scenario: %s" % scenario_config.description
                               ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by karthikcharan83** [comment]
@tdouthat please try using version 2.7 of Python. I believe that the print error is associated with version 3 of Python. Additional dependencies required by popgen include: PyYAML>=3.11, numpy>=1.9.2, scipy>=0.15.1, and pandas>=0.16.1.

**Comment by tdouthat** [comment]
Dr. konduri, I have both installed so that could be the problem. I'll let
you know.

Thank you for answering so quickly.

ThD
